### ISSUE TITLE
Peformance degredation when using msgpackr instead of JSON with large files

### ISSUE THREAD

**Issue by purplecandy** [kriszyp/msgpackr#128]
Hey, we have been experimenting with `msgpackr` and there are some clear benefits in the size of serialised payload but the performance of serializing and deserializing large payloads is worse when compared to `JSON`.  I'm not sure if that's the expected but I wanted to see if we are doing something incorrect on our side?

Here's the reproducible example: [Codesandbox Link](https://codesandbox.io/p/devbox/experimental-msgpackr-tkdrqx?file=%2Findex.js%3A17%2C47)

I have shared the repo with an example json but we have roughly the same size of payloads and in-fact more complex in nature

**Comment by kriszyp** [comment]
It is true that different data is going to have different performance characteristics. In this case, there is some de-optimization that occurs due to a mix of strings can't be fully encoded with one-byte-per-char strings.

I don't know if you can use mspgackr for both encoding and decoding. If you can, you can get significant performance gains from using the record extension (it was almost twice as fast with my tests of our data):

```
const packr = new Packr(); // this has the record extension enabled by default
packr.pack(...);
packr.unpack(...);
```

Also worth noting that encode=pack and decode=unpack, they are just aliases for each other.
