### ISSUE TITLE
🔴 pack do not work when encoding large ArrayBuffers / Blobs

### ISSUE THREAD

**Issue by rvion** [kriszyp/msgpackr#20]
Hi, I found a bug while packing something like: `{name: 'test', content: Blob(900Mo)}`:

the resulting packed message is only 8Ko 
also, it crashes when decoding on server, and returns {} when decoding on the client

note that it works for smaller files (~500Mo).

*message EDITED because my first repro was buggy* 

see 
- this message instead with a way simpler repro: https://github.com/kriszyp/msgpackr/issues/20#issuecomment-778310595
- (or this for a slightly more complex one https://github.com/kriszyp/msgpackr/issues/20#issuecomment-778301351 )

**Comment by kriszyp** [comment]
The issue is that a File/Blob isn't directly serializable (at least synchronously). It does have an `arrayBuffer()` method that can be used to start loading the contents of the file, and returns a promise to its completion. So I think you would probably want your example code to work like this (otherwise you are just serializing an object that can retrieve data about the file, that doesn't have any of its "own" properties to serialize):
```
  onChange={(ev) => {
      const file = ev.target.files![0]
      file.arrayBuffer().then(buffer => { // load the contents from the file
        const packed = pack(buffer)  // serialize the contents
        console.log('packed size', packed)
      })
  }}
```

Unpacking/deserializing the resulting buffer from your example, which is only 3 bytes, not 8Kb, to an empty object makes sense. I am not sure I understand how this would be crashing your server. When I try deserializing the buffer [222,0,0] on Node, I get an empty object, without any error. Are you getting an error when trying to deserialize buffer [222,0,0]? Or are you sending something else? The 8Kb you are referring to may be to the backing buffer store, not the actual target data.

Anyway, hopefully serializing the full file contents will work better.

Also, I can also add some better error handling that would detect an attempt to serialize a File/Blob, and give an appropriate warning.

**Comment by rvion** [comment]
Hi @kriszyp , thanks for the quick answer.

Arg My minimal repro example is just wrong, sorry; 
The bug and the 8kb buffer really exists. 

here is it the corect minimal repro code:  

```tsx
            <input
                type="file"
                onChange={async (ev) => {
                    const file = ev.target.files![0]
                    console.log('| A. file', file)
                    console.log('| B. file size', file.size)
                    const sourceBuff = await file.arrayBuffer() // <== here, I await the buffer
                    const packed = pack(sourceBuff)
                    console.log('| C. packed size', packed.length)
                    const unpacked: Uint8Array = unpack(packed)
                    console.log('| D. unpacked', unpacked)
                }}
            />
```

![image](https://user-images.githubusercontent.com/2150990/107792686-b0c0b880-6d55-11eb-9ee5-fb9a4588bf02.png)

That is what I was doing in my code; I just simplified it wrongly when writing the example.

**Comment by rvion** [comment]
here is an even more precise repro to avoid other issues:


```tsx
            <input
                type="file"
                onChange={async (ev) => {
                    const file = ev.target.files![0]
                    console.log('| A. file:', file)
                    console.log('| B. file size:', file.size)
                    const buff = await file.arrayBuffer()
                    console.log('| B2. check buff type:', buff.constructor.name)
                    const sizeCheck = new Uint8Array(buff).length
                    console.log('| B3. check buff size:', sizeCheck)
                    const packed = pack(buff)
                    console.log('| C. packed size:', packed.length)
                    const unpacked = unpack(packed)
                    console.log('| D. unpacked:', unpacked)
                    console.log('| E. unpacked buff size:', unpacked.length)
                }}
            />
```

so it happens between those two lines:

```tsx
                    console.log('| B3. check buff size:', sizeCheck)
                    const packed = pack(buff)
                    console.log('| C. packed size:', packed.length)
```

with a 500Mb file  => it works 🟢

![image](https://user-images.githubusercontent.com/2150990/107794401-b28b7b80-6d57-11eb-9b9c-4de815eb69d0.png)

with a 1000Mb file => it fails 🔴

![image](https://user-images.githubusercontent.com/2150990/107795090-8a504c80-6d58-11eb-9e47-3bc0f420939f.png)

**Comment by rvion** [comment]
same result with: 

![image](https://user-images.githubusercontent.com/2150990/107795851-7c4efb80-6d59-11eb-9f7e-6dd574a1b3e7.png)

**Comment by rvion** [comment]
I'm trying to rule out exterior causes, so here are some more infos : 

- I have > 16 free Gb of RAM
- chrome should support larger files (I anyway have an error message when I try to load an unsupported file)

![image](https://user-images.githubusercontent.com/2150990/107796226-e7003700-6d59-11eb-929b-c77bd1f9677c.png)

Tell me if I can help in any way

**Comment by rvion** [comment]
🔴🔴 here is an even simpler repro with no external dependencies :

ping @kriszyp 

🟢 works with `200_000_000`
🔴 fails with `700_000_000`

```tsx
            <button
                onClick={async (ev) => {
                    const DATA = new Uint8Array(200_000_000).fill(1)
                    console.log('| A. buff size:', DATA.length)
                    const packed = pack(DATA)
                    console.log('| C. packed size:', packed.length)
                    const unpacked = unpack(packed)
                    console.log('| D. unpacked:', unpacked)
                    console.log('| E. unpacked buff size:', unpacked.length)
                }}
            >
                TEST
            </button>
```


![image](https://user-images.githubusercontent.com/2150990/107796767-832a3e00-6d5a-11eb-9350-7b9b98fe22f6.png)


![image](https://user-images.githubusercontent.com/2150990/107797038-c5ec1600-6d5a-11eb-963b-b874fae87d0c.png)

**Comment by kriszyp** [comment]
Thank you for the detailed explanation! Sorry for my earlier misunderstanding. Anyway, should be fixed in v1.2.5. I would note that it looks like the maximum size of an ArrayBuffer (and thus Uint8Array and other buffer views) is about 2GB. Also, I think there can be some performance bottlenecks with buffers near that size that I will look into optimizing.

**Comment by rvion** [comment]
> hould be fixed in v1.2.5

Amazing, thanks !

> Also, I think there can be some performance bottlenecks with buffers near that size that I will look into optimizing.

Optimization for those kind of buffers would indeed be a great improvement for me. 

Thanks again !

**Comment by kriszyp** [comment]
1.2.6 should have significantly improved buffer performance (about 8x fast in the browser, by my estimates).

**Comment by rvion** [comment]
wow, thanks you so much ! 🎉
