### ISSUE TITLE
No standard handling of JS dates

### ISSUE THREAD

**Issue by manast** [kriszyp/msgpackr#41]
It seems as if dates are not encoded in the same standard as other msgpack libraries, so for example the following code yields an error:
```
import { Packr } from 'msgpackr';
import { unpack } from 'msgpack';
const packer = new Packr({
  useRecords: false,
  encodeUndefinedAsNil: true,
});

const msg = {
  date: new Date(),
};

unpack(packer.pack(msg));
```

Error:
```
unpack(packer.pack(msg));
^
TypeError: Encountered unknown MesssagePack object type
```

It could be the case that msgpack does not implement the standard correctly, however I am getting the same error when decoding the encoded data using redis msgpack decoder.

**Comment by kriszyp** [comment]
Ok, I added tests for date interoperability with `msgpack-lite`, `@msgpack/msgpack`, and `msgpack` packages. Here is what I found:

- `@msgpack/msgpack` - This seems to perfectly interoperate and round-trip dates with msgpackr. Besides msgpackr (of course :) ), this is best maintained JS MessagePack library, I believe, so this is probably pretty strong verification that msgpackr is properly handling dates.
- `msgpack-lite` - This does not interoperate; msgpack-lite seems to serialize dates using extension type 13, and 9 bytes of data. They list this in their documentation (https://github.com/kawanet/msgpack-lite), but it definitely does not match the MessagePack specification which indicates dates are supposed to be encoded with extension type -1/0xff.
- `msgpack` - This library seems to make no attempt to serialize dates in a way that can round-trip back to actual JS dates, and simply serializes dates as strings. As far as I can this library has no support for MessagePack's specified date extension, or even extensions at all.

Here is how msgpackr encodes a date, and again, reading the MessagePack specification, I believe this is correct:

`<d7 ff bc 59 c6 00 61 65 77 30>`

I could add an option to serialize dates as strings, like `msgpack` does, to help with interoperability. Obviously that is an inferior way to handle dates since it is lossly in terms of type preservation, and less efficient, but if that could help with compatibility.
