### ISSUE TITLE
Unpacking messages with records option from another library

### ISSUE THREAD

**Issue by quentin-sommer** [kriszyp/msgpackr#58]
Hi,
I'm trying to unpack messages produced by msgpackr from a python app. I'd like to use the records option because it greatly reduces the sizes of my messages. I've had some trouble reading it: https://github.com/msgpack/msgpack-python/issues/496
and the result are low level extension objects. I'm not at all familiar how msgpack works so my question is how difficult do you think it would it be for me to build a classic python dictionnary/list with the results of the parsing?

Quentin

**Comment by kriszyp** [comment]
First, the description of msgpackr's record extension is here, if you are looking to implement this: https://github.com/kriszyp/msgpackr#record-structure-extension-definition
I am not real familiar with Python, but I think the difficulty would depend on if you need to implement both serialization and parsing, or just parsing. I believe just implementing parsing should be easier than implementing serialization (and also would be easier if you use the default maximums for number of records that always uses one-byte record ids).

If reducing message size is the goal, another option you might consider is using the associated [CBOR project](https://github.com/kriszyp/cbor-x) if you can find a python library that supports [CBOR packed](https://datatracker.ietf.org/doc/html/draft-ietf-cbor-packed) extension. From a quick search, I don't see any such libraries, so that might not help.

**Comment by quentin-sommer** [comment]
Thank you for your answer! I'm afraid I'm not good enough with msgpack to implement the parsing from scratch myself. I was hoping I could patch it together using the current parsing output of the msgpack python library but it seems it's not outputting enough data to figure out the records definitions so I'll just stick to a regular msgpack.
